(global-set-key (kbd "C-c k") 'windmove-up)
(global-set-key (kbd "C-c j") 'windmove-down)
(global-set-key (kbd "C-c h") 'windmove-left)
(global-set-key (kbd "C-c l") 'windmove-right)
(global-set-key (kbd "C-c .") 'evil-mode)
;(add-hook 'eshell-mode-hook
;  (lambda ()
;    (local-set-key (kbd "C-z") 'bury-buffer)))
(setq mac-command-modifier 'super)
(define-key key-translation-map (kbd "s-x") (kbd "M-x"))
(define-key key-translation-map (kbd "s-p") (kbd "C-c C-p"))
(define-key key-translation-map (kbd "s-r") (kbd "C-x C-r"))
(define-key key-translation-map (kbd "s-w") (kbd "C-g"))
(define-key key-translation-map (kbd "s-b") (kbd "C-x C-b"))
(define-key key-translation-map (kbd "s-n") (kbd "C-n"))
(define-key key-translation-map (kbd "s-R") (kbd "C-c C-r"))
(define-key key-translation-map (kbd "s-.") (kbd "C-c C-."))
;(define-key key-translation-map (kbd "s-z") (kbd "C-z"))
(define-key key-translation-map (kbd "s-j") (kbd "C-c j"))
(define-key key-translation-map (kbd "s-k") (kbd "C-c k"))
(define-key key-translation-map (kbd "s-l") (kbd "C-c l"))
(define-key key-translation-map (kbd "s-h") (kbd "C-c h"))
(define-key key-translation-map (kbd "s-v") (kbd "C-c C-."))
(define-key key-translation-map (kbd "s-s") (kbd "C-x C-s"))
